export default [
  {
    _id: "621df50398ac3976a6f9dcec",
    productName: "BLACK FOREST CAKE",
    SKUID: "e7und43m4l07zk3d1",
    GST: 95.4,
    HS_CODE: "1905 90 10",
    vendorId: "61993ea26c19cf2ee44fbd14",
    category: "cakes and bakery",
    type: "Fresh cream cake",
    eggless: "",
    msgOnTheCake: "",
    imageName: "FCBlackforestcake_001",
    imgurl: "https://d1x0t3m3tl1ewa.cloudfront.net/FCBlackforestcake_001.jpg",
    altText: "Black forest birthday cake",
    reviews: "",
    productDescription:
      "Our signature Black forest cake is as good as a cake can get. Swathe...",
    sellingPrice: 530,
    price: 625,
    UOM: "Kg",
    weight: 1,
    productTags: "Array",
    isAvailable: "true",
  },
  {
    _id: "621df50398ac3976a6f9dcec",
    productName: "WHITE FOREST CAKE",
    SKUID: "e7und43m4l07zk3d1",
    GST: 95.4,
    HS_CODE: "1905 90 10",
    vendorId: "61993ea26c19cf2ee44fbd14",
    category: "cakes and bakery",
    type: "Fresh cream cake",
    eggless: "",
    msgOnTheCake: "",
    imageName: "FCBlackforestcake_001",
    imgurl: "https://d1x0t3m3tl1ewa.cloudfront.net/FCWhiteforestcake_001.jpg",
    altText: "Black forest birthday cake",
    reviews: 4.5,
    productDescription:
      "Our signature Black forest cake is as good as a cake can get. Swathe...",
    sellingPrice: 530,
    price: 625,
    UOM: "Kg",
    weight: 1,
    productTags: "Array",
    isAvailable: "true",
  },
  {
    _id: "621df50398ac3976a6f9dcec",
    productName: "CHOCOLATE CAKE",
    SKUID: "e7und43m4l07zk3d1",
    GST: 95.4,
    HS_CODE: "1905 90 10",
    vendorId: "61993ea26c19cf2ee44fbd14",
    category: "cakes and bakery",
    type: "Fresh cream cake",
    eggless: "",
    msgOnTheCake: "",
    imageName: "FCBlackforestcake_001",
    imgurl: "https://d1x0t3m3tl1ewa.cloudfront.net/FCChocolatecake_001.jpg",
    altText: "Black forest birthday cake",
    reviews: 4.5,
    productDescription:
      "Our signature Black forest cake is as good as a cake can get. Swathe...",
    sellingPrice: 530,
    price: 625,
    UOM: "Kg",
    weight: 1,
    productTags: "Array",
    isAvailable: "true",
  },
];
